/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.management.system;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DHEERAJ PRAKASH . S
 */
public class LOGIN_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_PAGE
     */
    public LOGIN_PAGE() {
        initComponents();
        setVisible(true);
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        PASSWORD_INPUT.requestFocus();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CONTAINER_PANEL = new javax.swing.JPanel();
        USERNAME_PANEL = new javax.swing.JPanel();
        USERNAME = new javax.swing.JLabel();
        USERNAME_INPUT_PANEL = new javax.swing.JPanel();
        USERNAME_INPUT = new javax.swing.JLabel();
        PASSWORD_PANEL = new javax.swing.JPanel();
        PASSWORD = new javax.swing.JLabel();
        PASSWORD_INPUT_PANEL = new javax.swing.JPanel();
        PASSWORD_INPUT = new javax.swing.JPasswordField();
        LOGIN_PANEL = new javax.swing.JPanel();
        LOGIN = new javax.swing.JLabel();
        CLOSE_PANEL = new javax.swing.JPanel();
        CLOSE = new javax.swing.JLabel();
        BACKGROUND_IMAGE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        CONTAINER_PANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        USERNAME_PANEL.setOpaque(false);

        USERNAME.setBackground(new java.awt.Color(204, 0, 0));
        USERNAME.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        USERNAME.setForeground(new java.awt.Color(255, 255, 255));
        USERNAME.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        USERNAME.setText("USERNAME:");

        javax.swing.GroupLayout USERNAME_PANELLayout = new javax.swing.GroupLayout(USERNAME_PANEL);
        USERNAME_PANEL.setLayout(USERNAME_PANELLayout);
        USERNAME_PANELLayout.setHorizontalGroup(
            USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, USERNAME_PANELLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        USERNAME_PANELLayout.setVerticalGroup(
            USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(USERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        CONTAINER_PANEL.add(USERNAME_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 144, -1, -1));

        USERNAME_INPUT_PANEL.setBackground(new java.awt.Color(240, 243, 159));

        USERNAME_INPUT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        USERNAME_INPUT.setText("KARISHMA AGENCIES");

        javax.swing.GroupLayout USERNAME_INPUT_PANELLayout = new javax.swing.GroupLayout(USERNAME_INPUT_PANEL);
        USERNAME_INPUT_PANEL.setLayout(USERNAME_INPUT_PANELLayout);
        USERNAME_INPUT_PANELLayout.setHorizontalGroup(
            USERNAME_INPUT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(USERNAME_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        USERNAME_INPUT_PANELLayout.setVerticalGroup(
            USERNAME_INPUT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(USERNAME_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CONTAINER_PANEL.add(USERNAME_INPUT_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 144, 340, 43));

        PASSWORD_PANEL.setOpaque(false);

        PASSWORD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PASSWORD.setForeground(new java.awt.Color(102, 255, 255));
        PASSWORD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PASSWORD.setText("PASSWORD:");

        javax.swing.GroupLayout PASSWORD_PANELLayout = new javax.swing.GroupLayout(PASSWORD_PANEL);
        PASSWORD_PANEL.setLayout(PASSWORD_PANELLayout);
        PASSWORD_PANELLayout.setHorizontalGroup(
            PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PASSWORD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PASSWORD_PANELLayout.setVerticalGroup(
            PASSWORD_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PASSWORD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CONTAINER_PANEL.add(PASSWORD_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 198, 225, 43));

        PASSWORD_INPUT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PASSWORD_INPUT.setEchoChar('*');
        PASSWORD_INPUT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PASSWORD_INPUTKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PASSWORD_INPUT_PANELLayout = new javax.swing.GroupLayout(PASSWORD_INPUT_PANEL);
        PASSWORD_INPUT_PANEL.setLayout(PASSWORD_INPUT_PANELLayout);
        PASSWORD_INPUT_PANELLayout.setHorizontalGroup(
            PASSWORD_INPUT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PASSWORD_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        PASSWORD_INPUT_PANELLayout.setVerticalGroup(
            PASSWORD_INPUT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PASSWORD_INPUT, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        CONTAINER_PANEL.add(PASSWORD_INPUT_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 198, 340, -1));

        LOGIN_PANEL.setBackground(new java.awt.Color(51, 255, 51));
        LOGIN_PANEL.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LOGIN_PANELMouseMoved(evt);
            }
        });

        LOGIN.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        LOGIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGIN.setText("LOGIN");
        LOGIN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LOGINMouseMoved(evt);
            }
        });
        LOGIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LOGINMousePressed(evt);
            }
        });

        javax.swing.GroupLayout LOGIN_PANELLayout = new javax.swing.GroupLayout(LOGIN_PANEL);
        LOGIN_PANEL.setLayout(LOGIN_PANELLayout);
        LOGIN_PANELLayout.setHorizontalGroup(
            LOGIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        LOGIN_PANELLayout.setVerticalGroup(
            LOGIN_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CONTAINER_PANEL.add(LOGIN_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 282, -1, -1));

        CLOSE_PANEL.setBackground(new java.awt.Color(255, 0, 51));
        CLOSE_PANEL.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CLOSE_PANELMouseMoved(evt);
            }
        });

        CLOSE.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        CLOSE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CLOSE.setText("X");
        CLOSE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CLOSEMouseMoved(evt);
            }
        });
        CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CLOSEMousePressed(evt);
            }
        });

        javax.swing.GroupLayout CLOSE_PANELLayout = new javax.swing.GroupLayout(CLOSE_PANEL);
        CLOSE_PANEL.setLayout(CLOSE_PANELLayout);
        CLOSE_PANELLayout.setHorizontalGroup(
            CLOSE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CLOSE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        CLOSE_PANELLayout.setVerticalGroup(
            CLOSE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CLOSE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CONTAINER_PANEL.add(CLOSE_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 50, 50));

        BACKGROUND_IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/COLOURFUL_BACKGROUND.jpg"))); // NOI18N
        BACKGROUND_IMAGE.setText("DFDS");
        BACKGROUND_IMAGE.setOpaque(true);
        CONTAINER_PANEL.add(BACKGROUND_IMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CONTAINER_PANEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CONTAINER_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void authenticator()
    {
        String password = new String(PASSWORD_INPUT.getPassword());
        if("HERA".equals(password))
        {
            DASHBOARD dashboard = new DASHBOARD();
            dispose();
        } 
        else {
             JOptionPane.showMessageDialog(this, "ACCESS DENIED", "WARNING", JOptionPane.WARNING_MESSAGE);
             PASSWORD_INPUT.setText("");
        }
    }
    private void LOGINMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMousePressed
        authenticator();
    }//GEN-LAST:event_LOGINMousePressed

    private void LOGINMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINMouseMoved
        Cursor cur1 = new Cursor(Cursor.HAND_CURSOR);
        LOGIN.setCursor(cur1);
    }//GEN-LAST:event_LOGINMouseMoved

    private void LOGIN_PANELMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGIN_PANELMouseMoved
        Cursor cur2 = new Cursor(Cursor.HAND_CURSOR);
        LOGIN_PANEL.setCursor(cur2);
    }//GEN-LAST:event_LOGIN_PANELMouseMoved

    private void CLOSE_PANELMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSE_PANELMouseMoved
        Cursor cur3 = new Cursor(Cursor.HAND_CURSOR);
        CLOSE_PANEL.setCursor(cur3);
    }//GEN-LAST:event_CLOSE_PANELMouseMoved

    private void CLOSEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseMoved
        Cursor cur4 = new Cursor(Cursor.HAND_CURSOR);
        CLOSE.setCursor(cur4);
    }//GEN-LAST:event_CLOSEMouseMoved

    private void CLOSEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMousePressed
     
        System.exit(0);
    }//GEN-LAST:event_CLOSEMousePressed

    private void PASSWORD_INPUTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PASSWORD_INPUTKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
            authenticator();
        }
    }//GEN-LAST:event_PASSWORD_INPUTKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LOGIN_PAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND_IMAGE;
    private javax.swing.JLabel CLOSE;
    private javax.swing.JPanel CLOSE_PANEL;
    private javax.swing.JPanel CONTAINER_PANEL;
    private javax.swing.JLabel LOGIN;
    private javax.swing.JPanel LOGIN_PANEL;
    private javax.swing.JLabel PASSWORD;
    private javax.swing.JPasswordField PASSWORD_INPUT;
    private javax.swing.JPanel PASSWORD_INPUT_PANEL;
    private javax.swing.JPanel PASSWORD_PANEL;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JLabel USERNAME_INPUT;
    private javax.swing.JPanel USERNAME_INPUT_PANEL;
    private javax.swing.JPanel USERNAME_PANEL;
    // End of variables declaration//GEN-END:variables
}
